dist: trusty
language: java
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
before_install:
- chmod +x gradlew

script: 
- "./gradlew clean build"
- "./gradlew test"
- "./gradlew bintrayUpload -PbintrayUser=$BINTRAY_USER -PbintrayApiKey=$BINTRAY_API_KEY"
deploy:
  provider: releases
  on:
    tags: true
    repo: sphrak/either
