dist: trusty
language: java
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
before_install:
- chmod +x gradlew
script:
- "./gradlew clean build"
- "./gradlew test"
deploy:
  provider: bintray
  file: "**/*Either.jar"
  script: "./gradlew bintrayUpload -PbintrayUser=$BINTRAY_USER -PbintrayApiKey=$BINTRAY_API_KEY"
  skip_cleanup: true
  on:
    tags: true
    repo: sphrak/Either
